readonlyrest:
  enable: true

  #ssl:
    #enable: true
    # keystore_file: "/tmp/ssl/self.jks"
    # keystore_pass: KEYSTORE_PASSWORD
    # key_pass: KEY_PASS

  response_if_req_forbidden: Dashboard access is forbidden. Invalid credentials.
  #rest.action.multi.allow_explicit_index: false

  access_control_rules:
  - name: Accept all request from trusted hosts
    type: allow
    hosts: [127.0.0.1, localhost, dashboard]
    verbosity: info

  - name: Check_mk
    type: allow
    #hosts: [CHECKHEALTH]
    actions: ["cluster:monitor/health"]
    verbosity: error

  - name: public_access
    type: allow
    indices: ["records", "indicators"]
    verbosity: error

  # We trust Kibana's server side process, full access granted via HTTP authentication
  - name: "::KIBANA-SRV::"
    groups: ["kibana_srv"]
    verbosity: error # don't log successful request

  - name: Kibana RW
    groups: ["kibana_rw"]
    kibana_access: rw
    kibana_index: .dashboards
    verbosity: error

  - name: Kibana_RO
#    groups: ["kibana_ro"]
    type: allow
    kibana_access: ro
    kibana_index: .dashboards
    verbosity: error

#  - name: Kibana_RO_strict
#    groups: ["kibana_ro_strict"]
#    type: allow
#    kibana_access: ro_strict
#    kibana_index: .dashboards
#    #indices: [".kibana"]
#    verbosity: error


  users:

  - username: kibana_rw
    auth_key: user:kibana
    groups: ["kibana_rw"]

#  - username: kibana_ro
#    auth_key: visitor:visitor
#    groups: ["kibana_ro"]

  - username: kibana_server
    # auth_key is good for testing, but replace it with `auth_key_sha256`!
    auth_key: user:kibana
    groups: ["kibana_srv"]
