version: '2'
services:

  dashboard:
    build:
      context: ./dashboard
      args:
          INSTALL_DASHBOARD_PATH: /mapped/drive/daobs-data-dir
          INSTALL_ETF_PATH: /var/local/etf
    ports:
      - "8080:8080"
    depends_on:
      - "elasticsearch"
    command: ["bash", "/wait-for-it.sh", "elasticsearch:9200", "-t", "0", "--", "/docker-entry.sh"]

  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearchData:/usr/share/elasticsearch/data
      - backups:/backups
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

      #must match below!
      KIBANA_RW_USERNAME: admin
      KIBANA_RW_PASSWORD: tZGVophwWaVM
      ENABLE_SSL: 0

      #in case you don't want public read only access, uncommend and set
      #KIBANA_RO_USERNAME: changeme
      #KIBANA_RO_PASSWORD: changeme


  kibana:
    build: ./kibana
    ports:
      - "5601:5601"
    volumes:
      - /backups:/backups
    depends_on:
      - "elasticsearch"
    command: ["bash", "/wait-for-it.sh", "elasticsearch:9200", "-t", "0", "--", "/docker-entry.sh"]
    environment:
      #must match above!
      KIBANA_RW_USERNAME: admin
      KIBANA_RW_PASSWORD: tZGVophwWaVM
      ENABLE_SSL: 0

      SSL_KEY: |-
          -----BEGIN RSA PRIVATE KEY-----
          changemechangemechangemechangemechangemechangemechangemechangeme
          changemechangemechangemechangemechangemechangemechangemechangeme
          changemechangemechangemechangemechangemechangemechangemechangeme
          changemechangemechangemechangemechangemechangemechangemechangeme
          -----END RSA PRIVATE KEY-----

      SSL_CERT: |-
          -----BEGIN CERTIFICATE-----
          changemechangemechangemechangemechangemechangemechangemechangeme
          changemechangemechangemechangemechangemechangemechangemechangeme
          changemechangemechangemechangemechangemechangemechangemechangeme
          changemechangemechangemechangemechangemechangemechangemechangeme
          -----END CERTIFICATE-----

      AUTH_CERT: |-
          -----BEGIN CERTIFICATE-----
          changemechangemechangemechangemechangemechangemechangemechangeme
          changemechangemechangemechangemechangemechangemechangemechangeme
          changemechangemechangemechangemechangemechangemechangemechangeme
          changemechangemechangemechangemechangemechangemechangemechangeme
          -----END CERTIFICATE-----

volumes:
    elasticsearchData:
       driver: local
    backups:
       driver: local
