version: '2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    container_name: elasticsearch

  elasticsearch-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    depends_on:
      - "elasticsearch"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch-node1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch,elasticsearch-node2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    container_name: elasticsearch-node1

  elasticsearch-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    depends_on:
      - "elasticsearch"
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - ${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    container_name: elasticsearch-node2

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.4
    #ports:
    #  - "5601:5601"
    expose:
      - "5601"
    volumes:
      - ${PWD}/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ${PWD}/kibana/wait-for-it.sh:/wait-for-it.sh
      - ${PWD}/kibana/docker-entry.sh:/docker-entry.sh
    depends_on:
      - "elasticsearch"
    command: ["bash", "/wait-for-it.sh", "elasticsearch:9200", "-t", "0", "--", "/docker-entry.sh"]

  dashboard:
    build:
      context: ../
    volumes:
       - daobsdir:/daobs-data-dir/
    #ports:
    #  - "8080:8080"
    #- m2:/usr/share/maven/ref/repository
    expose:
      - "8080"
    depends_on:
      - "kibana"
    command: ["bash", "/wait-for-it.sh", "kibana:5601", "-t", "0", "--", "/docker-entry.sh"]

  nginx:
    hostname: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${SSL_CERTS_DIR}/${SSL_PUB}:/etc/nginx/certs/cert.crt
      - ${SSL_KEY_DIR}/${SSL_PRIV}:/etc/nginx/private/priv.key
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/nginx-ssl.conf:/etc/nginx/nginx.conf
      - ./nginx/wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - "dashboard"

volumes:
    esdata:
       driver: local
    esdata1:
       driver: local
    esdata2:
       driver: local
    daobsdir:
       driver: local
    #m2:
    #   driver: local
