version: '2'
services:

  dashboard:
    image: inspiremif/daobs:2.0.x
    volumes:
       - daobsdir:/daobs-data-dir/
    expose:
      - "8080"
    depends_on:
      - "kibana"
    command: ["bash", "/wait-for-it.sh", "kibana:5601", "-t", "0", "--", "/docker-entry.sh"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    expose:
      - "9200"
      - "9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.1
    expose:
      - "5601"
    volumes:
      - ${PWD}/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ${PWD}/kibana/wait-for-it.sh:/wait-for-it.sh
      - ${PWD}/kibana/docker-entry.sh:/docker-entry.sh
    depends_on:
      - "elasticsearch"
    command: ["bash", "/wait-for-it.sh", "elasticsearch:9200", "-t", "0", "--", "/docker-entry.sh"]

  nginx:
    hostname: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${SSL_CERTS_DIR}/${SSL_PUB}:/etc/nginx/certs/cert.crt
      - ${SSL_KEY_DIR}/${SSL_PRIV}:/etc/nginx/private/priv.key
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/nginx-ssl.conf:/etc/nginx/nginx.conf
      - ./nginx/wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - "dashboard"

volumes:
    esdata:
       driver: local
    daobsdir:
       driver: local
