version: '2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.3
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/wait-for-it.sh:/wait-for-it.sh
      - ./kibana/docker-entry.sh:/docker-entry.sh
    depends_on:
      - "elasticsearch"
    command: ["bash", "/wait-for-it.sh", "elasticsearch:9200", "-t", "0", "--", "/docker-entry.sh"]

  dashboard:
    build:
      context: ./dashboard
      args:
          INSTALL_ETF_PATH: /var/local/etf
          INSTALL_DASHBOARD_PATH: /daobs-data-dir/
    volumes:
       - /mapped/drive/daobs-data-dir:/daobs-data-dir/
    ports:
      - "8080:8080"
    depends_on:
      - "kibana"
    command: ["bash", "/wait-for-it.sh", "kibana:5601", "-t", "0", "--", "/docker-entry.sh"]


  nginx:
    hostname: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./nginx/assets/certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - "dashboard"

volumes:
    elasticsearchData:
       driver: local

