version: '2'
services:

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    ports:
      - "5601:5601"

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/nginx-ssl.conf:/etc/nginx/nginx.conf
