version: '2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.3
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  dashboard:
    build:
      context: ./dashboard
      args:
          INSTALL_ETF_PATH: /var/local/etf
          INSTALL_DASHBOARD_PATH: /daobs-data-dir/
    volumes:
       - /mapped/drive/daobs-data-dir:/daobs-data-dir/
    ports:
      - "8080:8080"
    depends_on:
      - "kibana"
    command: ["bash", "/wait-for-it.sh", "kibana:5601", "-t", "0", "--", "/docker-entry.sh"]

volumes:
    elasticsearchData:
       driver: local

