version: '2'
services:

  sandbox-dashboard:
    build:
      context: .
      args:
        WEBAPP_NAME: dashboard
    image: inspiremif/daobs-eea-dashboard-sandbox:latest

  official-dashboard:
    build:
      context: .
      args:
        WEBAPP_NAME: official
    image: inspiremif/daobs-eea-dashboard-official:latest

  elasticsearch:
    build:
      context: ./elasticsearch
    image: inspiremif/elasticsearch:latest

  kibana:
    build:
      context: ./kibana
    image: inspiremif/kibana:latest

  cerebro:
    build:
      context: ./cerebro
    image: inspiremif/cerebro:latest

  sysctl:
    network_mode: none
    image: rawmind/alpine-sysctl:0.1
    privileged: true
    environment:
      - "SYSCTL_KEY=vm.max_map_count"
      - "SYSCTL_VALUE=262144"
