version: '2'
services:

  dashboard:
    image: inspiremif/daobs:2.0.x
    volumes:
       - daobsdir:/daobs-data-dir/
    expose:
      - "8080"
    depends_on:
      - "kibana"
    command: ["bash", "/wait-for-it.sh", "kibana:5601", "-t", "0", "--", "/docker-entry.sh"]
    container_name: dashboard

  elasticsearch:
    build:
      context: ./elasticsearch/
    volumes:
      - esdata:/usr/share/elasticsearch/data
      #- ${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    environment:
      - NODE_NAME=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTICSEARCH_MASTER=YES
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    container_name: elasticsearch

  elasticsearch-node1:
    build:
      context: ./elasticsearch/
    depends_on:
      - "elasticsearch"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      #- ${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - NODE_NAME=elasticsearch-node1
      - DISCOVERY_ZEN="elasticsearch,elasticsearch-node2"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTICSEARCH_MASTER=NO
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    container_name: elasticsearch-node1

  elasticsearch-node2:
    build:
      context: ./elasticsearch/
    depends_on:
      - "elasticsearch"
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      #- ${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - NODE_NAME=elasticsearch-node2
      - DISCOVERY_ZEN="elasticsearch"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTICSEARCH_MASTER=YES
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    container_name: elasticsearch-node2

  cerebro:
    image: snuids/cerebro:v0.7.1
    depends_on:
      - "elasticsearch"
    volumes:
      - ./cerebro/config/application.conf:/opt/cerebro/conf/application.conf
    container_name: cerebro

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.5
    expose:
      - "5601"
    volumes:
      - ${PWD}/kibana/config/kibana.1.yml:/usr/share/kibana/config/kibana.yml
      - ${PWD}/kibana/wait-for-it.sh:/wait-for-it.sh
      - ${PWD}/kibana/docker-entry.sh:/docker-entry.sh
    depends_on:
      - "elasticsearch"
    command: ["bash", "/wait-for-it.sh", "elasticsearch:9200", "-t", "0", "--", "/docker-entry.sh"]
    container_name: kibana

  nginx:
    hostname: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${SSL_CERTS_DIR}/${SSL_PUB}:/etc/nginx/certs/cert.crt
      - ${SSL_KEY_DIR}/${SSL_PRIV}:/etc/nginx/private/priv.key
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/nginx-ssl.conf:/etc/nginx/nginx.conf
      - ./nginx/wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - "dashboard"
    container_name: nginx

volumes:
    esdata:
       driver: local
    esdata1:
       driver: local
    esdata2:
       driver: local
    daobsdir:
       driver: local
