version: '2'
services:

  sandbox-dashboard:
    build:
      context: .
      args:
        WEBAPP_NAME: dashboard
    image: inspiremif/daobs-eea-dashboard-sandbox:latest

  official-dashboard:
    build:
      context: .
      args:
        WEBAPP_NAME: official
    image: inspiremif/daobs-eea-dashboard-official:latest

  elasticsearch:
    build:
      context: ./elasticsearch
    image: inspiremif/elasticsearch:latest
