elasticsearch.url: 'http://elasticsearch:9200'

server.host: '0.0.0.0'

server.name: kibana
#server.host: "0"

server.basePath: "/daobs/dashboard"

kibana.index: ".dashboards"

regionmap:
  layers:
     - name: "EU countries"
       url: "/daobs/assets/data/europe.geojson"
       attribution: "NaturalEarth"
       fields:
          - name: "NAME"
            description: "Full country name"
          - name: "ISO_A2"
            description: "ISO 2 letters code"
          - name: "ISO_A3"
            description: "ISO 3 letters code"

elasticsearch.username: "user"
elasticsearch.password: "kibana"

xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.ml.enabled: false
xpack.graph.enabled: false
xpack.watcher.enabled: false

server.ssl.enabled: false
